import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createStore } from '../server/db.js';
import { legacyNormalized, legacyRaw, seedLegacyDatabase } from './legacy-fixture.js';

test('V0.2 migration: V0.1 observations, identities, settings, manual classifications and queued work remain intact', () => {
  const directory = mkdtempSync(join(tmpdir(), 'appeye-v02-legacy-'));
  const path = join(directory, 'legacy.sqlite');
  seedLegacyDatabase(path);
  let store = createStore(path);
  try {
    const verify = () => {
      assert.equal(store.one('PRAGMA quick_check')?.quick_check, 'ok');
      assert.equal(store.one('SELECT value FROM metadata WHERE key=?', 'dataset')?.value, 'live');
      assert.equal(store.listApps().total, 3);
      assert.deepEqual([7, 8, 9].map(id => store.getApp(id)?.classification), ['confirmed', 'excluded', 'candidate']);
      assert.ok([7, 8, 9].every(id => store.getApp(id)?.manualOverride === true));
      assert.ok([7, 8, 9].every(id => store.getApp(id)?.classificationSource === 'legacy'));
      const app = store.getApp(7)!;
      assert.equal(app.externalId, legacyNormalized.externalId);
      assert.equal(app.country, 'th');
      assert.equal(app.store, 'google-play');
      assert.equal(app.firstSeenAt, '2026-01-01T00:00:00.000Z');
      assert.equal(app.releasedAt, legacyNormalized.releasedAt);
      assert.equal(app.lastFetchedAt, '2026-01-03T00:00:00.000Z');
      assert.equal(app.updateCount, 1);
      assert.equal(store.getApp(8)?.lastError, 'Legacy failure must remain visible');
      const snapshots = store.listSnapshots(7);
      assert.equal(snapshots.total, 2);
      assert.deepEqual(snapshots.snapshots.map(item => item.id), [12, 11]);
      assert.deepEqual(snapshots.snapshots[0].raw, legacyRaw);
      assert.equal(snapshots.snapshots[0].data.version, '1.1.0');
      const change = store.listChanges({ appId: 7 }).changes[0];
      assert.equal(change.id, 21);
      assert.equal(change.snapshotId, 12);
      assert.equal(change.oldValue, '1.0.0');
      assert.equal(change.newValue, '1.1.0');
      const review = store.listReviews(7).reviews[0];
      assert.equal(store.listReviews(7).total, 1);
      assert.equal(review.id, 31);
      assert.equal(review.text, 'Preserved synthetic review');
      assert.deepEqual(review.raw, { unknownReviewField: ['kept'] });
      assert.equal(store.getJob(41)?.status, 'queued');
      assert.equal(store.getJob(41)?.nextRunAt, '2099-01-01T00:00:00.000Z');
      assert.equal(store.getJob(42)?.status, 'failed');
      assert.equal(store.getJob(42)?.attempts, 3);
      assert.equal(store.getJob(42)?.error, 'Legacy upstream failure');
      assert.equal(store.getCountry('th')?.name, '泰国旧配置');
      assert.equal(store.getCountry('th')?.language, 'en');
      assert.equal(store.getCountry('th')?.intervalHours, 48);
      assert.equal(store.getCountry('th')?.enabled, false);
      assert.deepEqual(store.getCountry('th')?.keywords, ['fixture loan']);
      assert.equal(store.one('SELECT last_scheduled_at FROM schedule_state WHERE country=? AND store=?', 'th', 'google-play')?.last_scheduled_at, '2026-01-03T00:00:00.000Z');
    };
    verify();
    store.backfillCurrentStoreData();
    store.backfillLoanAnalyses();
    assert.deepEqual(store.getApp(7)?.storeData, legacyRaw);
    assert.deepEqual([7, 8, 9].map(id => store.getApp(id)?.classification), ['confirmed', 'excluded', 'candidate']);
    assert.equal(store.backfillLoanAnalyses(), 0);
    const migrations = store.all('SELECT version FROM schema_migrations ORDER BY version');
    store.close();
    store = createStore(path);
    verify();
    assert.deepEqual(store.all('SELECT version FROM schema_migrations ORDER BY version'), migrations);
  } finally { store.close(); rmSync(directory, { recursive: true, force: true }); }
});
